tabs -> 2 spaces in all bash files

diff --git a/.bin/bz2gz b/.bin/bz2gz
--- a/.bin/bz2gz
+++ b/.bin/bz2gz
@@ -1,30 +1,49 @@
 #!/bin/bash
 
-if [ -z "$1" ] || [ "$1" = "--keep" ] && [ -z "$2" ]; then
-    echo "Usage: `basename $0` [--keep] <files>"
-    exit 1
-fi
-
-keep=""
-if [ "$1" = "--keep" ]; then
-    keep="keep"
-    shift
-fi
-
 green="\033[01;32m"
 red="\033[01;31m"
 none="\033[00m"
 ok="[  ${green}ok${none}  ]"
 fail="[ ${red}fail${none} ]"
 
-while [ ! -z "$1" ]; do
-    ifile="$1"
-    ofile="`echo "$1" | sed 's/bz2$/gz/g'`"
-    if [ "$ifile" = "$ofile" ]; then
-        ofile="$ifile.gz"
-    fi
-    [ ! -f "$ifile" ] && echo -e "$fail $ifile does not exist!" || (bzip2 --test -- "$ifile" > /dev/null 2>&1 && (bzip2 -d < "$ifile" | gzip --best > "$ofile" && (echo -e "$ok $ifile -> $ofile"; [ -z "$keep" ] && rm -f -- "$ifile") || echo -e "$fail $ifile -> $ofile")) || echo -e "$fail $ifile is not bzip2 compressed"
-    shift
-done
+keep=false
 
-exit 0
+if [[ "${1}" = '--keep' ]]; then
+  keep=true
+  shift
+fi
+
+if [[ -z "${1}" ]]; then
+  echo "Usage: `basename ${0}` [--keep] <files>"
+  exit 1
+fi
+
+while [[ -n "${1}" ]]; do
+  ifile="${1}"
+  ofile="${1%gz}"bz2
+
+  if [[ "${ifile}" = "${ofile}" ]]; then
+    ofile="${ifile}.bz2"
+  fi
+
+  if [[ ! -f "${ifile}" ]]; then
+    echo -e "${fail} ${ifile} does not exist!"
+    continue
+  fi
+
+  if bzip2 --test -- "${ifile}" >/dev/null 2>&1; then
+    if bzip2 -d < "${ifile}" | gzip --best > "${ofile}"; then
+      echo -e "${ok} ${ifile} -> ${ofile}"
+
+      if ! ${keep}; then
+        rm -f -- "${ifile}"
+      fi
+    else
+      echo -e "${fail} ${ifile} -> ${ofile}"
+    fi
+  else
+    echo "${fail} ${ifile} is not bzip2 compressed!"
+  fi
+
+  shift
+done
diff --git a/.bin/tgz b/.bin/tgz
--- a/.bin/tgz
+++ b/.bin/tgz
@@ -1,35 +1,35 @@
 #!/bin/bash
 
 if [[ -z "${1}" ]]; then
-	echo "Usage: `basename ${0}` <file.tar.gz> [files...]"
-	exit 1
+  echo "Usage: `basename ${0}` <archive.tar.gz> [files...]"
+  exit 1
 fi
 
 if [[ -z "${2}" ]]; then
-	set "${1}" "${1}"
+  set "${1}" "${1}"
 fi
 
 out="${1%/}"
 shift
 
 case ${out} in
-	*.tgz | *.tar.gz)
-		tar -c -- "${*}" | gzip --best > "${out}"
-		ret=$?
-		;;
-	*)
-		tar -c -- "${*}" | gzip --best > "${out}.tar.gz"
-		ret=$?
-		;;
+  *.tgz | *.tar.gz)
+    tar -c -- "${*}" | gzip --best > "${out}"
+    ret=$?
+    ;;
+  *)
+    tar -c -- "${*}" | gzip --best > "${out}.tar.gz"
+    ret=$?
+    ;;
 esac
 
 case ${ret} in
-	0)
-		echo 'Done!'
-		;;
-	*)
-		echo 'Unknown error!'
-		;;
+  0)
+    echo 'Done!'
+    ;;
+  *)
+    echo 'Unknown error!'
+    ;;
 esac
 
 exit ${ret}
diff --git a/.bin/txz b/.bin/txz
--- a/.bin/txz
+++ b/.bin/txz
@@ -1,29 +1,35 @@
 #!/bin/bash
 
-if [ $# -eq "1" ]; then
-    set "$1" "$1"
-elif [ $# -lt "2" ]; then
-    echo "Usage: `basename $0` <file.tar.bz2> [files...]"
-    exit 1
+if [[ -z "${1}" ]]; then
+  echo "Usage: `basename ${0}` <archive.tar.xz> [files...]"
+  exit 1
 fi
 
-outfile=`echo "$1" | sed 's/\/$//g'`
-files=""
+if [[ -z "${2}" ]]; then
+  set "${1}" "${1}"
+fi
+
+out="${1%/}"
 shift
 
-while [ ! -z "$1" ]; do
-    files="$files `echo "$1" | sed 's/\/$//g'`"
-    shift
-done
-
-case $outfile in
-    *.tbz2 | *.tar.bz2)
-        tar -c -- $files | lzma --best > $outfile || rm -rf -- $outfile
-        ;;
-    *)
-        tar -c -- $files | lzma --best > $outfile.tar.bz2 || rm -rf -- $outfile.tar.bz2
-        ;;
+case ${out} in
+  *.txz | *.tar.xz)
+    tar -c -- "${*}" | lzma --best > "${out}"
+    ret=$?
+    ;;
+  *)
+    tar -c -- "${*}" | lzma --best > "${out}.tar.xz"
+    ret=$?
+    ;;
 esac
 
-echo "Done!"
-exit 0
+case ${ret} in
+  0)
+    echo 'Done!'
+    ;;
+  *)
+    echo 'Unknown error!'
+    ;;
+esac
+
+exit ${ret}
diff --git a/.bin/unix2dos b/.bin/unix2dos
--- a/.bin/unix2dos
+++ b/.bin/unix2dos
@@ -1,8 +1,8 @@
 #!/bin/bash
 
-if [ -z "$1" ]; then
-    echo "Usage: `basename $0` <files>"
-    exit 1
+if [[ -z "${1}" ]]; then
+  echo "Usage: `basename ${0}` <files>"
+  exit 1
 fi
 
 green="\033[01;32m"
@@ -11,9 +11,18 @@ none="\033[00m"
 ok="[  ${green}ok${none}  ]"
 fail="[ ${red}fail${none} ]"
 
-while [ ! -z "$1" ]; do
-    [ ! -f "$1" ] && echo -e "$fail $1 does not exist" || (sed -i 's/$/'"`echo -e '\r'`/" "$1" && echo -e "$ok $1" || echo -e "$fail $1")
-    shift
+while [[ -n "${1}" ]]; do
+  if [[ ! -f "${1}" ]]; then
+    echo -e "${fail} ${1} does not exist"
+  else
+    if sed -i 's/$/'"`echo -e '\r'`/" "${1}"; then
+      echo -e "${ok} ${1}"
+    else
+      echo -e "${fail} ${1}"
+    fi
+  fi
+
+  shift
 done
 
 exit 0
