remove useless git utils, add text-table

diff --git a/.bin/git-export b/.bin/git-export
--- a/.bin/git-export
+++ b/.bin/git-export
@@ -1,49 +1,57 @@
 #!/bin/bash
 
+#
+# usage
+#
+
+usage() {
+  echo "Usage: git export [options] [tree-ish]"
+  echo ''
+  echo 'Options:'
+  echo '  -h, --help            Print this message and exit'
+  echo '  -r, --remote=remote   Export from remote repo'
+  echo '  -f, --format=format   Set output format [tar.gz tgz tar zip]'
+  echo '  -o, --output=file     Set output file [stdout]'
+  exit ${1}
+}
+
+#
+# parse command line arguments
+#
+
 REMOTE=''
 OUTPUT=''
 FORMAT='tar.gz'
 ARGS=()
 
-usage() {
-  echo "usage: git export [options] [tree-ish]" >&2
-  echo '' >&2
-  echo 'options:' >&2
-  echo '  -h, --help            print this message and exit' >&2
-  echo '  -r, --remote=remote   export from remote repo' >&2
-  echo '  -f, --format=format   set output format [tar.gz tgz tar zip]' >&2
-  echo '  -o, --output=file     set output file [stdout]' >&2
-  exit 1
-}
-
-PARSE=true
+PARSE='true'
 while [[ -n "${1}" ]]; do
   if ${PARSE}; then
     case "${1}" in
-      -h)
+      -h|--help)
         usage 0;;
-      -r|--remote)
-        REMOTE="${2}"; shift;;
       -r*)
         REMOTE="${1:2}";;
       --remote=*)
         REMOTE="${1:9}";;
-      -f|--format)
-        FORMAT="${2}"; shift;;
+      -r|--remote)
+        REMOTE="${2}"; shift;;
       -f*)
         FORMAT="${1:2}";;
       --format=*)
         FORMAT="${1:9}";;
-      -o|--output)
-        OUTPUT="${2}"; shift;;
+      -f|--format)
+        FORMAT="${2}"; shift;;
       -o*)
         OUTPUT="${1:2}";;
       --output=*)
         OUTPUT="${1:9}";;
+      -o|--output)
+        OUTPUT="${2}"; shift;;
       --)
-        PARSE=false;;
+        PARSE='false';;
       -*)
-        echo "${0}: invalid option ${1:0:2}" >&2; echo >&2; usage; exit 1;;
+        echo "${0}: invalid option: ${1}" >&2; echo >&2; usage 1 >&2;;
       *)
         ARGS+=("${1}");;
     esac
@@ -55,6 +63,10 @@ while [[ -n "${1}" ]]; do
 done
 
 set -- "${ARGS[@]}"
+
+#
+# Do some actual work
+#
 
 TREE="${1}"
 TREE="${TREE:-master}"
diff --git a/.bin/git-lf b/.bin/git-lf
--- a/.bin/git-lf
+++ b/.bin/git-lf
@@ -1,28 +1,92 @@
 #!/bin/bash
 
-# set the internal field spereator to line break, so that we can iterate easily over the verify-pack output
-IFS=$'\n';
+#
+# usage
+#
 
-# list all objects including their size, sort by size, take top 25
-objects=`git verify-pack -v .git/objects/pack/pack-*.idx | grep -v chain | sort -k3nr | head -n 25`
+usage() {
+  echo 'Usage: git lf [options]'
+  echo
+  echo 'Options:'
+  echo '  -h, --help            Print this message and exit'
+  echo '  -t, --top=N           Take top N (default: 20)'
+  exit ${1}
+}
 
-output='Size,Compressed,SHA,Location'
-for y in ${objects}
-do
-  # extract the size in kilobytes
-  size=$((`echo ${y} | cut -f 5 -d ' '`/1024))
+#
+# parse command line arguments
+#
 
-  # extract the compressed size in kilobytes
-  compressed_size=$((`echo ${y} | cut -f 6 -d ' '`/1024))
+TOP='20'
+ARGS=()
 
-  # extract the SHA
-  sha=`echo ${y} | cut -f 1 -d ' '`
+PARSE='true'
+while [[ -n "${1}" ]]; do
+  if ${PARSE}; then
+    case "${1}" in
+      -h|--help)
+        usage 0;;
+      -t*)
+        TOP="${1:2}";;
+      --top=*)
+        TOP="${1:5}";;
+      -t|--top=)
+        TOP="${2}"; shift;;
+      --)
+        PARSE='false';;
+      -*)
+        echo "${0}: invalid option: ${1}" >&2; echo >&2; usage 1 >&2;;
+      *)
+        ARGS+=("${1}");;
+    esac
+  else
+    ARGS+=("${1}")
+  fi
 
-  # find the objects location in the repository tree
-  other=`git rev-list --all --objects | grep ${sha}`
-
-  # append to teh output
-  output="${output}\n${size}k,${compressed_size}k,${other}"
+  shift
 done
 
-echo -e ${output} | column -t -s ', '
+set -- "${ARGS[@]}"
+
+#
+# check args
+#
+
+if [[ -z "${TOP}" || ! "${TOP}" =~ ^[0-9]+$ ]]; then
+  echo "git-lf: Invalid TOP value: ${TOP}" >&2
+  echo >&2
+  usage 1>&2
+fi
+
+if [[ "${TOP}" = '0' ]]; then
+  TOP='2147483647'  # 2^31 - 1
+fi
+
+#
+# do some actual work
+#
+
+GIT_DIR="${PWD}"
+while [[ ! -e "${GIT_DIR}/.git" && "${GIT_DIR}" != '/' && -n "${GIT_DIR}" ]]; do
+  GIT_DIR="${GIT_DIR%/*}"
+done
+
+if [[ -z "${GIT_DIR}" || "${GIT_DIR}" = '/' ]]; then
+  echo 'git-lf: not a git repository!' >&2
+  exit 1
+fi
+
+GIT_DIR="${GIT_DIR}/.git"
+
+{
+  echo 'SHA|Size|Packed|Path'
+  echo ':separator:'
+  git verify-pack -v ${GIT_DIR}/objects/pack/pack-*.idx | grep ' blob ' | sort -k3nr | head -n ${TOP} | while read OBJECT; do
+    set -- ${OBJECT}
+    SHA="${1}"
+    UNPACKED_SIZE="${3}"
+    PACKED_SIZE="${4}"
+    FILE=$(git --git-dir="${GIT_DIR}" rev-list --all --objects | grep "${SHA}" | cut -f2 -d' ')
+    echo "${SHA}|${UNPACKED_SIZE}|${PACKED_SIZE}|${FILE}"
+  done
+} | text-table -a2:right -a3:right
