blah

diff --git a/.bin/grok b/.bin/grok
--- a/.bin/grok
+++ b/.bin/grok
@@ -9,11 +9,11 @@ usage() {
   echo "  ${0} [options]"
   echo
   echo 'Options:'
-  echo '  -h, --help            Print this message'
-  echo '  --server=S            SSH server (required if default is not set)'
-  echo '  --local-port=P        Set local port (required)'
-  echo '  --remote-port=P       Set remote port (optional)'
-  echo '  --save-default        Save server option to ~/.grok/server'
+  echo '  -h, --help                Print this message'
+  echo '  -s S, --server=S          SSH server (required if default is not set)'
+  echo '  -l P, --local-port=P      Set local port (required)'
+  echo '  -r P, --remote-port=P     Set remote port (optional)'
+  echo '  -D, --save-default        Save server option to ~/.grok/server'
   exit "${1}"
 }
 
@@ -40,30 +40,23 @@ while [[ -n "${1}" ]]; do
       -h|--help)
         usage 0;;
 
-      --server)
-        SERVER="${2}"; shift;;
-      --server=*)
-        SERVER="${1:9}";;
+      --server=*)  SERVER="${1:9}";;
+      -s|--server) SERVER="${2}"; shift;;
+      -s*)         SERVER="${1:2}";;
 
-      --local-port)
-        LOCAL_PORT="${2}"; shift;;
-      --local-port=*)
-        LOCAL_PORT="${1:13}";;
+      --local-port=*)  LOCAL_PORT="${1:13}";;
+      -l|--local-port) LOCAL_PORT="${2}"; shift;;
+      -l*)             LOCAL_PORT="${1:2}";;
 
-      --remote-port)
-        REMOTE_PORT="${2}"; shift;;
-      --remote-port=*)
-        REMOTE_PORT="${1:14}";;
+      -r|--remote-port) REMOTE_PORT="${2}"; shift;;
+      --remote-port=*)  REMOTE_PORT="${1:14}";;
+      -r*)              REMOTE_PORT="${1:2}";;
 
-      --save-default)
-        SAVE_DEFAULT='true';;
+      -D|--save-default) SAVE_DEFAULT='true';;
 
-      --)
-        PARSE='false';;
-      -*)
-        echo "${0}: invalid option: ${1}" >&2; echo >&2; usage 1 >&2;;
-      *)
-        ARGS+=("${1}");;
+      --) PARSE='false';;
+      -*) echo "${0}: invalid option: ${1}" >&2; echo >&2; usage 1 >&2;;
+      *)  ARGS+=("${1}");;
     esac
   else
     ARGS+=("${1}")
@@ -103,4 +96,4 @@ fi
 # Do the magic.
 #
 
-ssh -TnNqR "${REMOTE_PORT}:localhost:${LOCAL_PORT}" "${ARGS[@]}" "${SERVER}"
+ssh -TnNqR "0.0.0.0:${REMOTE_PORT}:localhost:${LOCAL_PORT}" "${ARGS[@]}" "${SERVER}"
