rename processes to threads in tarball

diff --git a/.bin/tarball b/.bin/tarball
--- a/.bin/tarball
+++ b/.bin/tarball
@@ -13,7 +13,7 @@ usage() {
   echo
   echo 'Options:'
   echo '  -c, --compression=C       Set compression to C (default: guess from extension)'
-  echo '  -p, --processes=N         Execute N parallel processes (default: 1)'
+  echo '  -t, --threads=N           Execute N parallel threads or processes (default: 4)'
   echo '  -1 .. -9                  Set compression level (default: 9)'
   echo '  --fast                    Alias of -1'
   echo '  --best                    Alias of -9'
@@ -26,7 +26,7 @@ usage() {
 
 COMPRESSION=
 COMPRESSION_LEVEL=9
-PROCESSES=1
+THREADS=4
 ARGS=()
 PARSE=true
 
@@ -45,12 +45,12 @@ while [[ -n "${1}" ]]; do
         COMPRESSION="${1:2}";;
       --compression=*)
         COMPRESSION="${1:14}";;
-      -p|--processes)
-        PROCESSES="${2}"; shift;;
-      -p*)
-        PROCESSES="${1:2}";;
-      --processes=*)
-        PROCESSES="${1:12}";;
+      -t|--threads)
+        THREADS="${2}"; shift;;
+      -t*)
+        THREADS="${1:2}";;
+      --threads=*)
+        THREADS="${1:10}";;
       -[1-9])
         COMPRESSION_LEVEL="${1:1}";;
       --fast)
@@ -93,11 +93,11 @@ if [[ -z "${1}" ]]; then
 fi
 
 #
-# Check processes value
+# Check threads value
 #
 
-if [[ ! "${PROCESSES}" =~ ^[0-9]+$ ]]; then
-  echo "${0}: invalid processes value: ${PROCESSES}" >&2
+if [[ ! "${THREADS}" =~ ^[0-9]+$ ]]; then
+  echo "${0}: invalid threads value: ${THREADS}" >&2
   echo >&2
   exit 1
 fi
@@ -115,27 +115,27 @@ fi
 
 case "${COMPRESSION}" in
   gz|tgz)
-    if [[ ${PROCESSES} -gt 1 ]]; then
+    if [[ ${THREADS} -gt 1 ]]; then
       COMPRESSOR=pigz
-      COMPRESSOR_ARGS=("-p${PROCESSES}" "-${COMPRESSION_LEVEL}")
+      COMPRESSOR_ARGS=("-p${THREADS}" "-${COMPRESSION_LEVEL}")
     else
       COMPRESSOR=gzip
       COMPRESSOR_ARGS=("-${COMPRESSION_LEVEL}")
     fi
     ;;
   bz2|tbz2)
-    if [[ ${PROCESSES} -gt 1 ]]; then
+    if [[ ${THREADS} -gt 1 ]]; then
       COMPRESSOR=pbzip2
-      COMPRESSOR_ARGS=("-p${PROCESSES}" "-${COMPRESSION_LEVEL}")
+      COMPRESSOR_ARGS=("-p${THREADS}" "-${COMPRESSION_LEVEL}")
     else
       COMPRESSOR=bzip2
       COMPRESSOR_ARGS=("-${COMPRESSION_LEVEL}")
     fi
     ;;
   lzma|xz|txz)
-    if [[ ${PROCESSES} -gt 1 ]]; then
+    if [[ ${THREADS} -gt 1 ]]; then
       COMPRESSOR=xz
-      COMPRESSOR_ARGS=("-T${PROCESSES}" "-${COMPRESSION_LEVEL}")
+      COMPRESSOR_ARGS=("-T${THREADS}" "-${COMPRESSION_LEVEL}")
     else
       COMPRESSOR=xz
       COMPRESSOR_ARGS=("-${COMPRESSION_LEVEL}")
